doc:
  property:
  - accountID: ''
  - g8client: ''
  - accountusers: ''
  - maxMemoryCapacity: ''
  - maxCPUCapacity: ''
  - description: ''
  - maxNumPublicIP: ''
  - maxDiskCapacity: ''
  - consumptionFrom: ''
  - consumptionTo: ''
  - consumptionData: ''
links:
  consume:
  - argname: g8client
    auto: true
    max: 100
    min: 0
    role: g8client
recurring: []
