language: python
sudo: enabled
dist: trusty
group: edge

# whitelist master branch only		
branches:		
  only:		
    - master

before_install:
  - sudo apt-get update

install: ./.travis_ci/prepare.sh

script: ./run_tests.sh

#after_success: /bin/bash upload_image.sh

#after_failure: /bin/bash upload_image.sh
