doc:
  property:
  - ovfUsername: ''
  - ovfCallbackUrl: ''
  - bootdiskSize: boot disk size in GB
  - ovfPassword: ''
  - description: ''
  - osImage: image as used in ms1
  - memory: memory in GB
  - sshPort: ''
  - ipPublic: ''
  - ipPrivate: ''
  - sshAddr: ''
  - disk: ''
  - ports: list of port forward to create src:dst
  - ovfPath: ''
  - sshLogin: ''
  - sshPassword: ''
  - sizeID: ''
  - ovfLink: ''
  - sshkey: ''
  - vdc: ''
  - machineId: ''
  - stackID: ''
  - vmHistory: ''
  - uservdc: 'List of vdc users that cann access the machine'
  - sshAuthorized: 'Flag to indicate whether the node has been ssh authorized or not'
  - vmInfoCallback: 'Callback url to send vm info after installing'
links:
  consume:
  - argname: disk
    auto: false
    max: 100
    min: '0'
    role: disk
  - argname: sshkey
    auto: true
    max: 100
    min: '1'
    role: sshkey
  - argname: uservdc
    auto: false
    max: 100
    min: 0
    role: uservdc
  parent:
    auto: true
    optional: false
    role: vdc
    argname: 'vdc'
recurring: []
