doc:
  property:
  - g8client: ''
  - devicename: ''
  - type: ''
  - maxIOPS: ''
  - description: ''
  - size: disk size in GB
  - ssdSize: ''
  - location: ''
  - totalBytesSec: ''
  - readBytesSec: ''
  - writeBytesSec: ''
  - totalIopsSec: ''
  - readIopsSec: ''
  - writeIopsSec: ''
  - totalBytesSecMax: ''
  - readBytesSecMax: ''
  - writeBytesSecMax: ''
  - totalIopsSecMax: ''
  - readIopsSecMax: ''
  - writeIopsSecMax: ''
  - sizeIopsSec: ''
  - diskId: ''

links:
  consume:
  - argname: g8client
    auto: true
    min: 1
    max: 100
    role: g8client

recurring: []
