doc:
  property:
  - startIPAddress: ''
  - endIPAddress: ''
  - vLANID: ''
  - publicSubnetCIDR: ''
  - gatewayIPAddress: ''
  - name: ''
  - vdc: ''
links:
  consume:
  - argname: vdc
    auto: true
    max: 100
    min: 0
    role: vdc
recurring: []
